// USER ACTION
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// CART ACTION
export const TOGGLE_CART_VISIBILITY = 'TOGGLE_CART_VISIBILITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
